#!/usr/bin/env python3

# Copyright Armijn Hemel
# Licensed under Apache 2.0, see LICENSE file for details
# SPDX-License-Identifier: Apache-2.0

import re

BAUD_RATES = [9600, 19200, 38400, 57600, 115200, 921600, 1500000]

# sometimes different names are used for the same brand
BRAND_REWRITE = {'FON Wireless': 'Fon Wireless',
                 'TenPao': 'Ten Pao',
                 'TP-Link': 'TP-LINK'}

# sometimes different names are used for the same country
COUNTRY_REWRITE = {'United States': 'USA',
                   'United Kingdom': 'UK'}

DISTRO_REWRITE = {'AsusWRT-Merlin': 'Asuswrt-Merlin',
                  'LEDE Project': 'LEDE'}

# a lookup table for default values for each of the
# identifiers which should be ignored.
# For some fields different default values were used over time.
DEFAULT_VALUE = {
    '802.1qvlan': ['<!-- Support for 802.1q vlan tagging, Leave blank for unknown -->'],
    'acqam1': ['<!-- AC-qam -->'],
    'acqam2': ['<!-- AC-qam -->'],
    'acqam3': ['<!-- AC-qam -->'],
    'addchip': ['<!-- Additional Chips -->'],
    'asin': ['<!-- ASIN number -->'],
    'asin2': ['<!-- ASIN number -->'],
    'asin3': ['<!-- ASIN number -->'],
    'asin4': ['<!-- ASIN number -->'],
    'asin5': ['<!-- ASIN number -->'],
    'asin_country': ['<!-- ASIN country -->'],
    'asin_country2': ['<!-- ASIN country -->'],
    'asin_country3': ['<!-- ASIN country -->'],
    'asin_country4': ['<!-- ASIN country -->'],
    'asin_country5': ['<!-- ASIN country -->'],
    'auto_mdix': ['<!-- mdix support -->', '<!-- Support automdix -->'],
    'availability': ['<!-- Market availability -->'],
    'axqam1': ['<!-- AX-qam -->'],
    'axqam2': ['<!-- AX-qam -->'],
    'axqam3': ['<!-- AX-qam -->'],
    'boardid': ['<!-- Board Identification, Leave blank for none -->'],
    'bootwait': ['<!-- On or Off, Leave blank for unknown -->'],
    'bus': ['<!-- 8-bit, 16-bit, 32-bit, 64-bit, Leave blank for none -->'],
    'buttons': ['<!-- buttons available -->'],
    'caption': ['<!-- tagline -->'],
    'caption2': ['<!-- 2nd tagleine -->', '<!-- 2nd tagline -->', '<!-- tagline 2 -->',
                 '<!-- tagline 2, Leave blank if unknown -->'],
    'countrymanuf': ['<!-- Country device was manufactured in -->'],
    'cpu1chip': ['<!-- cpu1chip full -->'],
    'cpu1chip1': ['<!-- Brand;Model;Extra, info; -->', '<!-- cpu1chip full -->',
                  '<!-- Brand;Model;Extra, info; -->', '<!-- cpu1chip1 full -->'],
    'cpu1modelfull': ['<!-- CPU1 Full chip info -->'],
    'cpu1spd': ['<!-- CPU1 speed, MHz, GHz, Leave blank if unknown -->', '<!-- undocumented -->',
                '<!-- In MHz, number only Leave blank if unknown -->'],
    'cpu1_cores': ['<!-- 1,2,3,4 -->'],
    'cpu1_type_rev': ['<!-- CPU1 type Revision, Leave blank for unknown -->'],
    'cpu1_type2_rev': ['<!-- CPU1 type Revision, Leave blank for unknown -->',
                       '<!-- CPU1 type2 Revision, Leave blank for unknown -->'],
    'cpu1_type': ['<!-- ARM,MIPS,x86-64,PowerPC, -->'],
    'cpu2brand': ['<!-- Brand? Leave blank if unknown -->'],
    'cpu2chip1': ['<!-- Brand;Model;Extra, info; -->'],
    'cpu2_cores': ['<!-- 1,2,3,4 -->'],
    'cpu2modelfull': ['<!-- CPU2 Full chip info -->'],
    'cpu2spd': ['<!-- CPU1 speed, MHz, GHz, Leave blank if unknown -->',
                '<!-- CPU2 speed, MHz, GHz, Leave blank if unknown -->',
                '<!-- CPU2 speed, Leave blank if unknown -->',
                '<!-- In MHz, number only Leave blank if unknown -->'],
    'cpu2_type': ['<!-- ARM,MIPS,x86-64,PowerPC, -->', '<!-- ARM,MIPS -->',
                  '<!-- ARM,MIPS,X86, -->', '<!-- ARM,MIPS, -->'],
    'cpu2_type_rev': ['<!-- CPU2 type Revision, Leave blank for unknown -->'],
    'ddwrtsupport': ['<!-- Supported, Not Supported, Incompatible, or leave blank for unknown -->'],
    'defaulip': ['<!-- ???.???.???.???, default IP Address -->'],
    'default_ch': ['<!-- Defaults channel(s) Radio(s) are set to -->'],
    'defaultlogin': ['<!-- default Login Name, Leave blank for unknown -->'],
    'defaultpass': ['<!-- default Password, Leave blank for unknown -->'],
    'defaultssid': ['<!-- default Wireless ID, Leave blank for unknown -->'],
    'dimensions': ['<!-- Size of device {{convert |length|x|widthordepth|x|height|in|mm}} -->',
                   '<!-- Size of device {{convert/3 |length|x|widthordepth|x|height|in|mm}} -->'],
    'dl': ['<!-- Download page url only -->'],
    'dx_sku': ['<!-- DealExtreme sku -->'],
    'ean': ['<!-- EAN number -->'],
    'ecc_id': ['<!-- eec-id -->'],
    'eoldate': ['<!-- End of Life date -->'],
    'estprice': ['<!-- Estimated retail price in US dollars -->'],
    'estreldate': ['<!-- Estimated release date -->'],
    'eth_cpu': ['<!-- true, -->', '<!-- true -->'],
    'eth1chip': ['<!-- Brand;Model;Extra, info; -->', '<!-- eth1chip full -->'],
    'eth2chip': ['<!-- Brand;Model;Extra, info; -->', '<!-- eth2chip full -->'],
    'eth3chip': ['<!-- Brand;Model;Extra, info; -->', '<!-- eth3chip full -->'],
    'eth4chip': ['<!-- Brand;Model;Extra, info; -->', '<!-- eth4chip full -->'],
    'ethchip4brand': ['<!-- Brand?, Leave blank if unknown -->'],
    'ethchip4modelfull': ['<!-- Ethernet4 full chip info -->'],
    'ethchip4model': ['<!-- Model?, Leave blank if unknown -->'],
    'eth_none': ['<!-- true, -->', '<!-- true -->'],
    'ethoui': ['<!-- Leave blank for unknown -->'],
    'ethstandard': ['<!-- IEEE 802.3?,IEEE 802.3,IEEE 802.3/3u,IEEE 802.3/3u/3ab,IEEE 802.3/3u/3x,IEEE 802.1x/3/3ab/3u/3x/3z -->'],
    'exp_M.2': ['<!-- Number of M.2 ports, Leave blank for none -->'],
    'exp_ata_num': ['<!-- Number of ATA Ports, Leave blank for none -->'],
    'exp_cf_num': ['<!-- Number Compact Flash Slots, Leave blank for none -->'],
    'exp_esata_num': ['<!-- Number of esata ports, Leave blank for none -->'],
    'exp_expcard_num': ['<!-- Number of Expresscard ports, Leave blank for none -->'],
    'exp_ide_num': ['<!-- Number of ide ports, Leave blank for none -->'],
    'exp_if_types': ['<!-- Expansion Interface types, Leave blank for none -->'],
    'exp_minipci_num': ['<!-- Number of Mini PCI Slots, Leave blank for none -->'],
    'exp_minipcie_num': ['<!-- Number of Mini PCIexpress Slots, Leave blank for none -->'],
    'exp_parallel': ['<!-- Number of parallel ports, Leave blank for none -->'],
    'exp_pcmcia_num': ['<!-- Number of pcmcia ports, Leave blank for none -->'],
    'exp_sata_num': ['<!-- Number of sata ports, Leave blank for none -->'],
    'exp_sdmmc_num': ['<!-- Number SD/MMC Slots, Leave blank for none -->'],
    'exp_sfp_num': ['<!-- Number of sfp ports, Leave blank for none -->'],
    'exp_sim_num': ['<!-- Number of sim Slots, Leave blank for none -->'],
    'exp_usb_num': ['<!-- Number of USB Ports, Leave blank for none -->'],
    'fcc_id': ['<!-- Federal Communication Commission Identification Number -->'],
    'fccapprovdate': ['<!-- FCCID approval date -->'],
    'fla1_num': ['<!-- 1,2,3,4 -->'],
    'fla1chip': ['<!-- Brand;Model;Extra, info; -->'],
    'fla1chipbrand': ['<!-- Brand? Leave blank if unknown -->'],
    'fla1chipmodelfull': ['<!-- Flash1 full chip info -->'],
    'fla1chipmodel': ['<!-- Model? Leave blank if unknown -->'],
    'fla2chip': ['<!-- Brand;Model;Extra, info; -->'],
    'fla2_num': ['<!-- 1,2,3,4 -->'],
    'fla2chipmodel': ['<!-- Model? Leave blank if unknown -->'],
    'fla2chipmodelfull': ['<!-- Flash2 full chip info -->'],
    'fla3chip': ['<!-- Brand;Model;Extra, info; -->'],
    'fla3_num': ['<!-- 1,2,3,4 -->'],
    'flags': ['<!-- flags, Leave blank for none -->'],
    'flash1maxsize': ['<!-- Maximum size firmware can be in bytes -->',
                      '<!-- Maximum size firmware -->'],
    'flash1size': ['<!-- Size of flash -->'],
    'flash1type': ['<!-- Parallel,Serial(SPI),NAND,Compact Flash -->',
                   '<!-- Parallel,Serial(SPI),SPI NOR,NAND,Compact Flash, -->'],
    'flash2maxsize': ['<!-- Maximum size firmware can be in bytes -->'],
    'flash2size': ['<!-- Size of flash -->', '<!-- 0.0625,0.125,0.25,0.5,1,2,4,8,16,32,64,128,256,512,1024,2048 -->'],
    'flash2type': ['<!-- Parallel,Serial(SPI),NAND,Compact Flash -->',
                   '<!-- Parallel,Serial(SPI),SPI NOR,NAND,Compact Flash, -->'],
    'flash3type': ['<!-- Parallel,Serial(SPI),SPI NOR,NAND,Compact Flash, -->'],
    'flash3maxsize': ['<!-- Maximum size firmware can be in bytes -->'],
    'flash3size': ['<!-- Size of flash -->'],
    'gargoylesupport': ['<!-- Supported, Not Supported, Incompatible, or leave blank for unknown -->'],
    'gpu1_cores': ['<!-- 1,2,3,4 -->'],
    'gpu1spd': ['<!-- gpu speed, MHz, GHz, Leave blank if unknown -->'],
    'gpu1_type': ['<!-- ARM,MIPS,x86-64,PowerPC, -->'],
    'gpu1_type_rev': ['<!-- GPU1 type Revision, Leave blank for unknown -->'],
    'homepage': ['<!-- Product page, Leave blank if unknown -->'],
    'icid': ['<!-- Industry Canada Identification number, Leave blank for unknown -->'],
    'image1': ['<!-- Image filename -->'],
    'image1_size': ['<!-- Image size, ex.150px -->', '<!-- Image size, ex.200px -->'],
    'image2': ['<!-- 2nd image, Leave blank if unknown -->'],
    'is_manuf': ['<!-- Yes or No -->', '<!-- Yes, or No, -->'],
    'jtag': ['<!-- Full JTAG info -->'],
    'jtagport': ['<!-- Yes or No, Leave blank for unknown -->'],
    'lan_speed': ['<!-- 10MbE,100MbE,1GbE, -->', '<!-- 10/100/1000 -->'],
    'lan2_speed': ['<!-- 10MbE,100MbE,1GbE, -->', '<!-- 10/100/1000 -->'],
    'led': ['<!-- Led colors and descriptions -->'],
    'manuf': ['<!-- Manufacturer -->'],
    'manuf_model': ['<!-- Manufacturer Model -->'],
    'manuf_rev': ['<!-- Manufacturer Revision -->'],
    'newegg': ['<!-- newegg item number -->', '<!-- Newegg number -->'],
    'nqam1': ['<!-- 600, 800, 900, 1000, -->', '<!-- 600, 750, 900, 1000 -->',
              '<!-- 600, 750, 900, 1000, -->', '<!-- 600,750,900 -->'],
    'nqam2': ['<!-- 600, 800, 900, 1000, -->', '<!-- 600, 750, 900, 1000 -->',
              '<!-- 600,750,900 -->'],
    'nqam3': ['<!-- 600, 800, 900, 1000, -->', '<!-- 600, 750, 900, 1000 -->',
              '<!-- 600, 750, 900, 1000, -->'],
    'nvramsize': ['<!-- 32, 60, 64, etc... in kb, Leave blank for unknown -->'],
    'openwrtsupport': ['<!-- Supported, Not Supported, Incompatible, or leave blank for unknown -->'],
    'oui': ['<!-- Wireless OUI -->', '<!-- Leave blank for unknown -->'],
    'portbasedvlan': ['<!-- Support for port based vlan tagging, Leave blank for unknown -->'],
    'pp': ['<!-- product page url only -->'],
    'price': ['<!-- Estimated retail price in US dollars -->'],
    'pwr_ac_hz': ['<!-- AC Hertz -->'],
    'pwr_amp_ac': ['<!-- AC Amps -->'],
    'pwr_amp_dc': ['<!-- DC Amps -->'],
    'pwr_barrel_inner': ['<!-- Inner barrel size in mm -->'],
    'pwr_barrel_len': ['<!-- Length of barrel -->'],
    'pwr_barrel_outer': ['<!-- Outer barrel size in mm -->'],
    'pwr_conn': ['<!-- Connector Type -->'],
    'pwr_poe_amp': ['<!-- POE Amps -->'],
    'pwr_poe': ['<!-- POE Volts -->'],
    'pwr_poe_type': ['<!-- Type of POE -->'],
    'pwr_pol': ['<!-- Connector polarity -->'],
    'pwr_vac': ['<!-- AC Volts -->'],
    'pwr_vdc': ['<!-- DC Volts -->'],
    'pwr_volt_type': ['<!-- VDC,VAC or POE -->', '<!-- VDC,VAC or POE, -->',
                      '<!-- VDC,VAC, or POE, -->'],
    'rad1_ant_conn': ['<!-- Leave blank for unknown -->'],
    'rad1cap': ['<!-- radio capabilities, Leave blank for none or unknown -->'],
    'rad1chip1': ['<!-- Brand;Model;Extra, info; -->', '<!-- full chip info -->'],
    'rad1chip1brand': ['<!-- Brand?, Leave blank if unknown -->'],
    'rad1chip1cpu': ['<!-- true, -->'],
    'rad1chip2': ['<!-- Brand;Model;Extra, info; -->', '<!-- full chip info -->'],
    'rad1chip3': ['<!-- Brand;Model;Extra, info; -->', '<!-- full chip info -->'],
    'rad1chip1modelfull': ['<!-- radio1 chip1 full info -->'],
    'rad1chip1model': ['<!-- Model?, Leave blank if unknown -->'],
    'rad1chip2modelfull': ['<!-- radio1 chip2 full info -->'],
    'rad1chip2model': ['<!-- Model?, Leave blank if unknown -->'],
    'rad1chip3brand': ['<!-- Brand?, Leave blank if unknown -->'],
    'rad1chip3modelfull': ['<!-- radio1 chip3 full info -->'],
    'rad1chip3model': ['<!-- Model?, Leave blank if unknown -->'],
    'rad1correv': ['<!-- core revision, Leave blank for none or unknown -->'],
    'rad1g': ['<!-- 54, 108, Maximum throughput rated at -->'],
    'rad1mod': ['<!-- Radio module name, optional link, Leave blank for none -->'],
    'rad1modif': ['<!-- Radio Module Interface Type, Leave blank for none -->'],
    'rad1oui': ['<!-- Only if different from above OUI -->'],
    'rad1n': ['<!-- 150, 300, 450, 600, Maximum throughput rated at -->',
              '<!-- 150, 300, 450, Maximum throughput rated at -->'],
    'rad1rxchains': ['<!-- Number of receive radio chains, Leave blank if unknown -->'],
    'rad1sstreams': ['<!-- Number of spatial data streams, Leave blank if unknown -->'],
    'rad1txchains': ['<!-- Number of transmit radio chains, Leave blank if unknown -->'],
    'rad2ay': ['<!-- Maximum throughput rated at -->'],
    'rad2cap': ['<!-- radio capabilities, Leave blank for none or unknown -->'],
    'rad2chip1': ['<!-- Brand;Model;Extra, info; -->'],
    'rad2chip1cpu': ['<!-- true, -->'],
    'rad2chip1modelfull': ['<!-- radio2 chip1 full info -->'],
    'rad2chip2': ['<!-- Brand;Model;Extra, info; -->', '<!-- full chip info -->'],
    'rad2chip3': ['<!-- Brand;Model;Extra, info; -->', '<!-- full chip info -->'],
    'rad2correv': ['<!-- core revision, Leave blank for none or unknown -->'],
    'rad2mod': ['<!-- Radio module name, optional link, Leave blank for none -->'],
    'rad2modif': ['<!-- Radio Module Interface Type, Leave blank for none -->'],
    'rad2oui': ['<!-- Only if different from above OUI -->'],
    'rad2_ant_conn': ['<!-- Leave blank for unknown -->'],
    'rad2rxchains': ['<!-- Number of receive radio chains, Leave blank if unknown -->'],
    'rad2sstreams': ['<!-- Number of spatial data streams, Leave blank if unknown -->'],
    'rad2txchains': ['<!-- Number of transmit radio chains, Leave blank if unknown -->'],
    'rad3cap': ['<!-- radio capabilities, Leave blank for none or unknown -->'],
    'rad3chip1': ['<!-- Brand;Model;Extra, info; -->'],
    'rad3chip1brand': ['<!-- Brand?, Leave blank if unknown -->'],
    'rad3chip1modelfull': ['<!-- radio3 chip1 full info -->'],
    'rad3chip1model': ['<!-- Model?, Leave blank if unknown -->'],
    'rad3chip2': ['<!-- Brand;Model;Extra, info; -->'],
    'rad3chip2brand': ['<!-- Brand?, Leave blank if unknown -->'],
    'rad3chip2modelfull': ['<!-- radio3 chip2 full info -->'],
    'rad3chip2model': ['<!-- Model?, Leave blank if unknown -->'],
    'rad3chip3': ['<!-- Brand;Model;Extra, info; -->'],
    'rad3chip3brand': ['<!-- Brand?, Leave blank if unknown -->'],
    'rad3chip3modelfull': ['<!-- radio3 chip3 full info -->'],
    'rad3chip3model': ['<!-- Model?, Leave blank if unknown -->'],
    'rad3correv': ['<!-- core revision, Leave blank for none or unknown -->'],
    'rad3modif': ['<!-- Radio Module Interface Type, Leave blank for none -->'],
    'rad3mod': ['<!-- Radio module name, optional link, Leave blank for none -->'],
    'rad3oui': ['<!-- Only if different from above OUI -->'],
    'rad3_ant_conn': ['<!-- Leave blank for unknown -->'],
    'rad4chip1': ['<!-- Brand;Model;Extra, info; -->'],
    'rad4chip2': ['<!-- Brand;Model;Extra, info; -->'],
    'rad4chip3': ['<!-- Brand;Model;Extra, info; -->'],
    'rad4_ant_conn': ['<!-- Leave blank for unknown -->'],
    'rad4modif': ['<!-- Radio Module Interface Type, Leave blank for none -->'],
    'rad4oui': ['<!-- Only if different from above OUI -->'],
    'ram1_num': ['<!-- Number of Ram chips -->'],
    'ram1chip': ['<!-- Brand;Model;Extra, info; -->'],
    'ram1chipbrand': ['<!-- Brand? Leave blank if unknown -->'],
    'ram1chipmodel': ['<!-- Model? Leave blank if unknown -->'],
    'ram1chipmodelfull': ['<!-- RAM1 full chip info -->'],
    'ram1size': ['<!-- Size of RAM -->'],
    'ram1spd': ['<!-- 3400,3333,3300,3200,3100,3000,2800,2666,2600,2400,2133,2000,1866,1600,1066,1333,800 -->'],
    'ram1type': ['<!-- DDR,DDR2,DDR3,DDR4 -->', '<!-- DDR,DDR2,DDR3,DDR4, -->'],
    'ram1type1': ['<!-- SO-DIMM,SDRAM -->', '<!-- SO-DIMM,SDRAM, -->'],
    'ram2_num': ['<!-- Number of Ram chips -->'],
    'ram2chip': ['<!-- Brand;Model;Extra, info; -->'],
    'ram2size': ['<!-- Size of RAM -->', '<!-- 2, 4, 8, 16, 32, 64, 128, 256, 512, etc... -->'],
    'ram2spd': ['<!-- 3400,3333,3300,3200,3100,3000,2800,2666,2600,2400,2133,2000,1866,1600,1066,1333,800 -->'],
    'ram2type': ['<!-- DDR,DDR2,DDR3,DDR4 -->', '<!-- DDR,DDR2,DDR3,DDR4, -->'],
    'ram2type1': ['<!-- SO-DIMM,SDRAM -->', '<!-- SO-DIMM,SDRAM, -->'],
    'ram3_num': ['<!-- Number of Ram chips -->'],
    'ram3spd': ['<!-- 3400,3333,3300,3200,3100,3000,2800,2666,2600,2400,2133,2000,1866,1600,1066,1333,800 -->'],
    'ram3type': ['<!-- DDR,DDR2,DDR3,DDR4 -->', '<!-- DDR,DDR2,DDR3,DDR4, -->'],
    'ram3type1': ['<!-- SO-DIMM,SDRAM -->', '<!-- SO-DIMM,SDRAM, -->'],
    'reldate': ['<!-- Release date -->'],
    'revision': ['<!-- Model Revision, Leave blank for none or unknown -->'],
    'serial': ['<!-- Full Serial info -->'],
    'series': ['<!-- Device series -->'],
    'sernum': ['<!-- First 4 or so for easy version identification -->'],
    'sp': ['<!-- Support page url only -->'],
    'specialfeat': ['<!-- Features that don\'t fit any place else, Leave blank for none -->'],
    'stock_bl_dist': ['<!-- bootloader distro -->'],
    'stock_bl_version': ['<!-- bootloader version -->'],
    'stock_bootloader': ['<!-- OEM Bootloader, BSP,CFE (128k),CFE,CFE (vender modified),U-Boot,U-Boot;3.3;Ralink,Redboot,ROME,RouterBOOT,Not Listed, Leave blank for unknown -->'],
    'stockbootloader': ['<!-- Name;Version;Distro -->'],
    'stockos': ['<!-- Name;Version;Distro -->'],
    'stock_os': ['<!-- OEM Operating System, Debian,eCos,ISOS,Linux,Nucleus RTOS,RouterOS,SlugOS,SuperTask!,ThreadX,μClinux,VxWorks,ZyNOS -->'],
    'stock_os_kern': ['<!-- OEM Operating System kernel revision -->'],
    'stock_os_sdk': ['<!-- OEM Operating System sdk revision -->'],
    'submodel': ['<!-- SubModel number, Leave blank for unknown -->',
                 '<!-- Submodel, Leave blank for none or unknown -->'],
    'submodelappend': ['<!-- yes for space -->', '<!-- yes, for space -->'],
    'subrevision': ['<!-- Model Subrevision, Leave blank for none or unknown -->'],
    'sup_jumbo': ['<!-- Jumbo frames support -->', '<!-- Support Jumbo frames -->'],
    'supportpage': ['<!-- Support page, Leave blank if unknown -->'],
    'sw_cpu': ['<!-- true, -->', '<!-- true -->'],
    'sw1chip': ['<!-- Brand;Model;Extra, info; -->', '<!-- Switch1 chip -->'],
    'switchmodelfull': ['<!-- Switch1 full chip info -->'],
    'tjtagsupport': ['<!-- Yes or No, Leave blank for unknown -->'],
    'tjtagversion': ['<!-- TJTAG Version number, Leave blank for unknown -->'],
    'tomatosupport': ['<!-- Supported, Not Supported, Incompatible, or leave blank for unknown -->'],
    'tomatousbsupport': ['<!-- Supported, Not Supported, Incompatible, or leave blank for unknown -->'],
    'tpfirmware': ['<!-- Third party firmware official support, AsusWRT-Merlin, CeroWrt, DD-WRT, DD-WRT (kong), DD-WRT (kongac), DD-WRT (kongarm), FreedomBox, FreshTomato-ARM, Gargoyle, LibreWrt, Oleg (wl500g), Oleg-ng (wl500g), OpenWrt, Tomato, Tomato RAF, Tomato (shibby), Tomato (Toastman), TomatoUSB, Wive-NG -->'],
    'totlan': ['<!-- total lan ports -->'],
    'totwan': ['<!-- total wan ports -->'],
    'upc': ['<!-- UPC number -->'],
    'us_id': ['<!-- US ID number -->', '<!-- US ID -->'],
    'usb_hub': ['<!-- USB hub compatibility -->'],
    'wan_speed': ['<!-- 10MbE,100MbE,1GbE, -->'],
    'wan2_speed': ['<!-- 10MbE,100MbE,1GbE, -->'],
    'weight': ['<!-- Weight of device {{convert|weight|oz|g}} -->'],
    'wikidevi': ['<!-- wikidevi.wi-cat.ru page, included underscores -->'],
    'wikipedia': ['<!-- [[wikipedia:Main Page|Wikipedia]] Leave blank for none -->'],
    'x86-64rev2': ['<!-- x86-64 Revision, Leave blank for unknown -->'],
}

# regular expression for ASIN
REGEX_ASIN = re.compile(r'^B[\d\w]{9}$')

# regular expression for an IPv4 address
REGEX_IP = re.compile(r'^\d+\.\d+\.\d+\.\d+$')

# regular expression for OUI
# https://en.wikipedia.org/wiki/Organizationally_unique_identifier
REGEX_OUI = re.compile(r'^[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}$')

# regular expression for finding connectors in
# serial port information sections
REGEX_SERIAL_CONNECTOR = re.compile(r'(JP?\d+)')

REGEX_SERIAL_PIN_HEADER = re.compile(r'(?:via )?(\d+)[ -](?:in|pln|pin|pad|pads) ?(?:header|connector)?')
REGEX_SERIAL_RJ45 = re.compile(r'RJ-?45( console)?')

# REGEX_LINUX_VERSION = re.compile(r'Linux version \d\.\d+\.\d+')

REGEX_BUSYBOX = re.compile(r'BusyBox v\d\.\d+')

# big lookup lists for chip manufacturers
CHIP_MANUFACTURERS = [
'2Wire',
'5V Technologies',
'ADMtek',
'Allwinner',
'Ambarella',
'AMCC',
'AMD',
'Amlogic',
'AMRISC',
'Annapurna Labs',
'Apple',
'Applied Micro',
'Atheros',
'Atmel',
'Axis',
'Beceem',
'Brecis',
'BridgeCo',
'Broadcom',
'Broadlight',
'Cavium',
'Celeno',
'Cirrus Logic',
'Conexant',
'Cortina Systems',
'Davicom',
'D-Link',
'EcoNet',
'Espressif',
'Freescale',
'GCT',
'Globespan Virata',
'Grain Media',
'HiSilicon',
'Hitachi',
'Hyperstone',
'IBM',
'iCatch',
'IDT',
'Ikanos',
'Infineon',
'Ingenic',
'Intel',
'Intellon',
'Intersil',
'Kendin',
'KeyASIC',
'Lantiq',
'Marvell',
'MediaTek',
'Micrel',
'Microchip',
'Mindspeed',
'Mitsumi',
'Motorola',
'Movidius',
'MStar',
'National Semiconductor',
'NEC',
'No Wires Needed',
'Nuvoton',
'nVIDIA',
'NXP',
'Octavo Systems',
'OmniVision',
'Ozmo Devices',
'Parrot',
'PLX Technology',
'PMC-Sierra',
'Prolific',
'Qualcomm',
'Qualcomm Atheros',
'Quantenna',
'Ralink',
'RDA',
'RDC',
'Realtek',
'Renesas',
'Rockchip',
'Samsung',
'SE',
'SEEQ',
'ShareWave',
'SiFlower',
'Sigma Designs',
'SigmaTel',
'Silicon Data',
'Skyviia',
'SonicWALL',
'Sonix',
'Star',
'ST-Ericsson',
'STMicro',
'Storlink',
'Synaptics',
'Texas Instruments',
'TrendChip',
'TriDuctor',
'Ubicom',
'VIA',
'Virata',
'Vitesse',
'VLSI',
'WavePlus',
'Winbond',
'ZyDAS',
]
